version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  api-gateway-service:
    type: boolean
    default: false
  auth-service:
    type: boolean
    default: false
  ui:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
        name: Trigger Workflows
        command: chmod + x ./circle_trigger.sh && ./circle_trigger.sh

  build:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project
      # This step is added only to show that we are in the package directory
      - run:
          name: Content
          command: |
            cat README.md
            echo "<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "Build << parameters.package_name >> ..."
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  api-gateway-service:
    when: << pipeline.parameters.api-gateway-service >>
    jobs:
      - build:
          name: api-gateway-service-build
          package_name: api-gateway-service
      - deploy:
          name: api-gateway-service-deploy
          package_name: api-gateway-service
          requires:
            - api-gateway-service-build
