http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth:
    host: localhost
    paths: /auth/*
  example:
    host: localhost
    paths: /example/*
serviceEndpoints:
  authService:
    url: "http://localhost:5000"
  exampleService:
    url: "http://localhost:5010"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - auth
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
              prependPath: true
              ignorePath: false
              stripPath: true
  example:
    apiEndpoints:
      - example
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: exampleService
              changeOrigin: true
              prependPath: true
              ignorePath: false
              stripPath: true
